describedBy:
  headers: 
#    Cookie:
#      displayName: token
#      description: Token, выданный пользователю при авторизации. Token можно получить в методах login и confirm_user.
#      type: string
#      required: true
#      example: aabbccddeeff00112233445566778899
  queryParameters:
    token:
      description: Token, выданный пользователю при авторизации. Token можно получить в методах login и confirm_user.
      type: string
      example: aabbccddeeff00112233445566778899
type: x-cookie