description: Проверка авторизации и получение данных пользователя
get:
  securedBy: [cookie]
  description: Получаем данные по авторизованному пользователю, параметры передавать не нужно, достаточно просто выполнить процедуру аутентификации по cookie.
