description: Подтверждение учетной записи пользователя по коду из письма
get:
  description: Подтверждение учетной записи пользователя по коду из письма. Код сбрасывается при вызове данного метода в не зависисмости от его правильности, что защищает от перебора кодов. По логике метод должен быть POST, но так как вызов идёт из письма мы используем метод GET.
  queryParameters:
    user_id:
      type: integer
      description: Идентификатор пользователя
      example: 1
      required: true
    confirm_code:
      type: string
      description: Код подтверждения
      example: aabbccddeeff00112233445566778899
      required: true