description: Предпросмотр вёрстки шаблона письма
get:
  securedBy: [cookie]
  description: Получения контента шаблона для предпросмотра
  queryParameters:
    id:
      type: integer
      description: Идентификатор шаблона
      example: 1
      required: true