description: Генерация архива с вёрсткой шаблона
get:
  securedBy: [cookie]
  description: Получение архива с вёрсткой шаблона
  queryParameters:
    id:
      type: integer
      description: Идентификатор шаблона
      example: 1
      required: true